# 2D periodic shear instability
# All dimensional values are cgs.
problem.name=kelvin-helmholtz
mesh.ndim=2
mesh.cells=16
mesh.level=1
runtime.stop_time=0.1
mesh.periodic=on
output.directory=output/kelvin-helmholtz
output.format=csv
output.every=10
