# 2D periodic initially isotropic M1 pulse
# All dimensional values are cgs.
problem.name=radiation-pulse
mesh.ndim=2
mesh.cells=8
mesh.level=1
runtime.stop_time=0.2
mesh.periodic=on
output.directory=output/radiation-pulse
output.format=csv
output.every=10
