# 1D periodic freely streaming M1 Gaussian
# All dimensional values are cgs.
problem.name=streaming
mesh.ndim=1
mesh.cells=32
mesh.level=1
runtime.stop_time=0.4
mesh.periodic=on
output.directory=output/streaming
output.format=csv
output.every=10
