# Problem-local manifests are the authority for supported build combinations.
if(CMAKE_SCRIPT_MODE_FILE)
  cmake_minimum_required(VERSION 3.22)
endif()

function(octo_problem name)
  cmake_parse_arguments(P "HYDRO;RADIATION;GRAVITY" "DEFAULT_DIMENSION" "DIMENSIONS" ${ARGN})
  if(P_UNPARSED_ARGUMENTS OR NOT P_DIMENSIONS OR NOT P_DEFAULT_DIMENSION)
    message(FATAL_ERROR "Invalid problem manifest: ${CMAKE_CURRENT_LIST_FILE}")
  endif()
  get_property(names GLOBAL PROPERTY OCTO_PROBLEMS)
  if(name IN_LIST names)
    message(FATAL_ERROR "Duplicate problem name: ${name}")
  endif()
  set_property(GLOBAL APPEND PROPERTY OCTO_PROBLEMS "${name}")
  set_property(GLOBAL PROPERTY OCTO_${name}_DIRECTORY "${CMAKE_CURRENT_LIST_DIR}")
  foreach(key DIMENSIONS DEFAULT_DIMENSION HYDRO RADIATION GRAVITY)
    set_property(GLOBAL PROPERTY OCTO_${name}_${key} "${P_${key}}")
  endforeach()
endfunction()

if(CMAKE_SCRIPT_MODE_FILE)
  file(GLOB_RECURSE manifests "${PROJECT_SOURCE_DIR}/bin/*/CMakeLists.txt")
else()
  file(GLOB_RECURSE manifests CONFIGURE_DEPENDS "${PROJECT_SOURCE_DIR}/bin/*/CMakeLists.txt")
endif()
foreach(manifest IN LISTS manifests)
  include("${manifest}")
endforeach()
get_property(problems GLOBAL PROPERTY OCTO_PROBLEMS)

function(octo_problem_sources)
  set(declarations "")
  set(entries "")
  set(sources "")
  foreach(name IN LISTS problems)
    foreach(key DIRECTORY DIMENSIONS HYDRO RADIATION GRAVITY)
      get_property(P_${key} GLOBAL PROPERTY OCTO_${name}_${key})
    endforeach()
    string(REPLACE "-" "_" symbol "${name}")
    set(reason "")
    set(flags "")
    foreach(module HYDRO RADIATION GRAVITY)
      if(P_${module})
        string(APPEND flags "true, ")
        if(NOT OCTOII_WITH_${module})
          string(APPEND reason "requires OCTOII_WITH_${module}=ON; ")
        endif()
      else()
        string(APPEND flags "false, ")
      endif()
    endforeach()
    if(NOT OCTOTIGERII_NDIM IN_LIST P_DIMENSIONS)
      string(APPEND reason "supported dimensions: ${P_DIMENSIONS}; select the corresponding octoII executable")
    endif()
    if(reason STREQUAL "")
      list(APPEND sources "${P_DIRECTORY}/problem.cpp")
      string(APPEND declarations "namespace ${symbol} { void problemDefaults(Config&); void validateProblem(Config const&); void initializeProblem(Snapshot&, Config const&, bool); ProblemBoundary problemBoundary(Config const&); verification::Reference problemReference(Config const&); }\n")
      set(hooks "${symbol}::problemDefaults, ${symbol}::validateProblem, ${symbol}::initializeProblem, ${symbol}::problemBoundary, ${symbol}::problemReference")
    else()
      set(hooks "nullptr, nullptr, nullptr, nullptr, nullptr")
    endif()
    string(APPEND entries "{\"${name}\", ${flags}\"${reason}\", ${hooks}},\n")
  endforeach()
  configure_file("${PROJECT_SOURCE_DIR}/cmake/problems.cpp.in" "${CMAKE_CURRENT_BINARY_DIR}/problems.cpp" @ONLY)
  set(problem_sources ${sources} PARENT_SCOPE)
endfunction()
