# Problem-local manifests are the authority for supported build combinations.
if(CMAKE_SCRIPT_MODE_FILE)
  cmake_minimum_required(VERSION 3.22)
endif()

function(octo_problem name)
  cmake_parse_arguments(P "HYDRO;RADIATION;GRAVITY" "DEFAULT_DIMENSION" "DIMENSIONS" ${ARGN})
  if(P_UNPARSED_ARGUMENTS OR NOT P_DIMENSIONS OR NOT P_DEFAULT_DIMENSION)
    message(FATAL_ERROR "Invalid problem manifest: ${CMAKE_CURRENT_LIST_FILE}")
  endif()
  get_property(names GLOBAL PROPERTY OCTO_PROBLEMS)
  if(name IN_LIST names)
    message(FATAL_ERROR "Duplicate problem name: ${name}")
  endif()
  set_property(GLOBAL APPEND PROPERTY OCTO_PROBLEMS "${name}")
  set_property(GLOBAL PROPERTY OCTO_${name}_DIRECTORY "${CMAKE_CURRENT_LIST_DIR}")
  foreach(key DIMENSIONS DEFAULT_DIMENSION HYDRO RADIATION GRAVITY)
    set_property(GLOBAL PROPERTY OCTO_${name}_${key} "${P_${key}}")
  endforeach()
endfunction()

if(CMAKE_SCRIPT_MODE_FILE)
  file(GLOB_RECURSE manifests "${PROJECT_SOURCE_DIR}/bin/*/CMakeLists.txt")
else()
  file(GLOB_RECURSE manifests CONFIGURE_DEPENDS "${PROJECT_SOURCE_DIR}/bin/*/CMakeLists.txt")
endif()
foreach(manifest IN LISTS manifests)
  include("${manifest}")
endforeach()
get_property(problems GLOBAL PROPERTY OCTO_PROBLEMS)
set(OCTOTIGERII_PROBLEM "sod" CACHE STRING "Problem implementation to build")
set_property(CACHE OCTOTIGERII_PROBLEM PROPERTY STRINGS ${problems})
if(NOT OCTOTIGERII_PROBLEM IN_LIST problems)
  message(FATAL_ERROR "Unknown problem '${OCTOTIGERII_PROBLEM}'. Choose: ${problems}")
endif()
foreach(key DIRECTORY DIMENSIONS DEFAULT_DIMENSION HYDRO RADIATION GRAVITY)
  get_property(PROBLEM_${key} GLOBAL PROPERTY OCTO_${OCTOTIGERII_PROBLEM}_${key})
endforeach()
set(OCTOTIGERII_NDIM "${PROBLEM_DEFAULT_DIMENSION}" CACHE STRING "Compile-time spatial dimension")
set_property(CACHE OCTOTIGERII_NDIM PROPERTY STRINGS ${PROBLEM_DIMENSIONS})
if(NOT OCTOTIGERII_NDIM IN_LIST PROBLEM_DIMENSIONS)
  message(FATAL_ERROR "${OCTOTIGERII_PROBLEM} supports ndim=${PROBLEM_DIMENSIONS}; requested ${OCTOTIGERII_NDIM}. Use a separate build directory per problem/dimension.")
endif()
if(PROBLEM_GRAVITY AND NOT OCTOTIGERII_NDIM STREQUAL "3")
  message(FATAL_ERROR "Gravity requires ndim=3")
endif()
if(CMAKE_SCRIPT_MODE_FILE)
  message(STATUS "Valid problem build: ${OCTOTIGERII_PROBLEM}, ${OCTOTIGERII_NDIM}D")
  return()
endif()
foreach(physics HYDRO RADIATION GRAVITY)
  if(PROBLEM_${physics})
    set(OCTOTIGERII_${physics} 1)
  else()
    set(OCTOTIGERII_${physics} 0)
  endif()
endforeach()
set(OCTOTIGERII_EXECUTABLE "octotigerII-${OCTOTIGERII_PROBLEM}-${OCTOTIGERII_NDIM}d")
configure_file("${PROJECT_SOURCE_DIR}/cmake/buildConfig.hpp.in"
  "${PROJECT_BINARY_DIR}/include/octotigerII/buildConfig.hpp" @ONLY)
message(STATUS "OctotigerII: ${OCTOTIGERII_PROBLEM}, ${OCTOTIGERII_NDIM}D -> ${OCTOTIGERII_EXECUTABLE}")
